/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_gnu_pilotlink_PilotLink */

#ifndef _Included_org_gnu_pilotlink_PilotLink
#define _Included_org_gnu_pilotlink_PilotLink
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_gnu_pilotlink_PilotLink
 * Method:    connect
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_gnu_pilotlink_PilotLink_connect
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_gnu_pilotlink_PilotLink
 * Method:    readSysInfo
 * Signature: (I)Lorg/gnu/pilotlink/SysInfo;
 */
JNIEXPORT jobject JNICALL Java_org_gnu_pilotlink_PilotLink_readSysInfo
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_gnu_pilotlink_PilotLink
 * Method:    readUserInfo
 * Signature: (I)Lorg/gnu/pilotlink/User;
 */
JNIEXPORT jobject JNICALL Java_org_gnu_pilotlink_PilotLink_readUserInfo
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_gnu_pilotlink_PilotLink
 * Method:    readAppInfo
 * Signature: (II)Lorg/gnu/pilotlink/RawAppInfo;
 */
JNIEXPORT jobject JNICALL Java_org_gnu_pilotlink_PilotLink_readAppInfo
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_gnu_pilotlink_PilotLink
 * Method:    getAppInfoBlock
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jobject JNICALL Java_org_gnu_pilotlink_PilotLink_getAppInfoBlock
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     org_gnu_pilotlink_PilotLink
 * Method:    writeUserInfo
 * Signature: (ILorg/gnu/pilotlink/User;)V
 */
JNIEXPORT void JNICALL Java_org_gnu_pilotlink_PilotLink_writeUserInfo
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     org_gnu_pilotlink_PilotLink
 * Method:    createDB
 * Signature: (IJLjava/lang/String;J)I
 */
JNIEXPORT jint JNICALL Java_org_gnu_pilotlink_PilotLink_createDB__IJLjava_lang_String_2J
  (JNIEnv *, jobject, jint, jlong, jstring, jlong);

/*
 * Class:     org_gnu_pilotlink_PilotLink
 * Method:    createDB
 * Signature: (IJLjava/lang/String;JII)I
 */
JNIEXPORT jint JNICALL Java_org_gnu_pilotlink_PilotLink_createDB__IJLjava_lang_String_2JII
  (JNIEnv *, jobject, jint, jlong, jstring, jlong, jint, jint);

/*
 * Class:     org_gnu_pilotlink_PilotLink
 * Method:    deleteDB
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_gnu_pilotlink_PilotLink_deleteDB
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     org_gnu_pilotlink_PilotLink
 * Method:    openDB
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_gnu_pilotlink_PilotLink_openDB
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     org_gnu_pilotlink_PilotLink
 * Method:    writeAppBlock
 * Signature: (II[BI)I
 */
JNIEXPORT jint JNICALL Java_org_gnu_pilotlink_PilotLink_writeAppBlock
  (JNIEnv *, jobject, jint, jint, jbyteArray, jint);

/*
 * Class:     org_gnu_pilotlink_PilotLink
 * Method:    getRecordCount
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_gnu_pilotlink_PilotLink_getRecordCount
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_gnu_pilotlink_PilotLink
 * Method:    getRecordByIndex
 * Signature: (III)Lorg/gnu/pilotlink/RawRecord;
 */
JNIEXPORT jobject JNICALL Java_org_gnu_pilotlink_PilotLink_getRecordByIndex
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_gnu_pilotlink_PilotLink
 * Method:    deleteRecordByIndex
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_org_gnu_pilotlink_PilotLink_deleteRecordById
  (JNIEnv *, jobject, jint, jint, jlong);

/*
 * Class:     org_gnu_pilotlink_PilotLink
 * Method:    writeRecord
 * Signature: (IILorg/gnu/pilotlink/Record;)I
 */
JNIEXPORT jint JNICALL Java_org_gnu_pilotlink_PilotLink_writeRecord
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     org_gnu_pilotlink_PilotLink
 * Method:    closeDB
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_gnu_pilotlink_PilotLink_closeDB
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_gnu_pilotlink_PilotLink
 * Method:    endSync
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_gnu_pilotlink_PilotLink_endSync
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_gnu_pilotlink_PilotLink
 * Method:    close
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_gnu_pilotlink_PilotLink_close
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_gnu_pilotlink_PilotLink
 * Method:    openConduit
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_gnu_pilotlink_PilotLink_openConduit
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_gnu_pilotlink_PilotLink
 * Method:    getResourceByIndex
 * Signature: (III)Lorg/gnu/pilotlink/RawRecord;
 */
JNIEXPORT jobject JNICALL Java_org_gnu_pilotlink_PilotLink_getResourceByIndex
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_gnu_pilotlink_PilotLink
 * Method:    writeResource
 * Signature: (IILorg/gnu/pilotlink/RawRecord;)V
 */
JNIEXPORT void JNICALL Java_org_gnu_pilotlink_PilotLink_writeResource
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     org_gnu_pilotlink_PilotLink
 * Method:    resetSystem
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_gnu_pilotlink_PilotLink_resetSystem
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_gnu_pilotlink_PilotLink
 * Method:    readDBList
 * Signature: (IIII)Lorg/gnu/pilotlink/DBInfo;
 */
JNIEXPORT jobject JNICALL Java_org_gnu_pilotlink_PilotLink_readDBList
  (JNIEnv *, jobject, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
